// Package dbsvc provisions managed databases.
package dbsvc

import (
	"fmt"
	"strconv"

	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/resource"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/util/intstr"

	"skifity/internal/kube"
	"skifity/internal/version"
)

// Engines the panel can provision.
const (
	EnginePostgres = "postgres"
	EngineRedis    = "redis"
	EngineMySQL    = "mysql"
)

// DefaultVersions are used when the user does not pick one. They are the
// current stable major of each, which is what someone starting a new project
// wants; an existing project can pin whatever it needs.
var DefaultVersions = map[string]string{
	EnginePostgres: "17",
	EngineRedis:    "7",
	EngineMySQL:    "11.4", // MariaDB, which is the drop-in the images ship
}

// DefaultPorts are what each engine listens on.
var DefaultPorts = map[string]int{
	EnginePostgres: 5432,
	EngineRedis:    6379,
	EngineMySQL:    3306,
}

// Spec describes a database to create.
type Spec struct {
	Name      string
	Namespace string
	// DatabaseID ties the Kubernetes objects back to the panel's record.
	DatabaseID string
	TeamID     string
	Engine     string
	Version    string
	Instances  int
	StorageGB  int
	// Username, Password and DatabaseName are generated by the panel.
	Username     string
	Password     string
	DatabaseName string
	CPURequestM  int
	MemRequestMB int
	MemLimitMB   int
	// StorageClass is set when cross-node storage is enabled.
	StorageClass string
}

// Defaults fills in what a caller left out.
func (s *Spec) Defaults() {
	if s.Version == "" {
		s.Version = DefaultVersions[s.Engine]
	}
	if s.Instances < 1 {
		s.Instances = 1
	}
	if s.StorageGB < 1 {
		s.StorageGB = 5
	}
	if s.CPURequestM == 0 {
		s.CPURequestM = 100
	}
	if s.MemRequestMB == 0 {
		s.MemRequestMB = 256
	}
	if s.MemLimitMB == 0 {
		s.MemLimitMB = 1024
	}
	if s.DatabaseName == "" {
		s.DatabaseName = "app"
	}
	if s.Username == "" {
		s.Username = "app"
	}
}

// Validate reports a spec Kubernetes would reject.
func (s Spec) Validate() error {
	if !kube.ValidLabel(s.Name) {
		return fmt.Errorf("database name %q is not usable as a Kubernetes name", s.Name)
	}
	switch s.Engine {
	case EnginePostgres, EngineRedis, EngineMySQL:
	default:
		return fmt.Errorf("%q is not an engine Skifity provisions", s.Engine)
	}
	if s.Password == "" {
		return fmt.Errorf("a database needs a password")
	}
	if s.Engine == EnginePostgres && s.Instances > 1 && s.Instances%2 == 0 {
		// CloudNativePG elects a primary; an even count gives no benefit over
		// the odd number below it and wastes a replica.
		return fmt.Errorf("use an odd number of PostgreSQL instances so a failover always has a majority")
	}
	return nil
}

// Labels identify the objects a database owns.
func (s Spec) Labels() map[string]string {
	return map[string]string{
		"app.kubernetes.io/name":        s.Name,
		"app.kubernetes.io/managed-by":  version.Binary,
		"app.kubernetes.io/component":   "database",
		version.LabelKey("database-id"): s.DatabaseID,
		version.LabelKey("team-id"):     s.TeamID,
		version.LabelKey("engine"):      s.Engine,
	}
}

// SecretName is where the credentials live in the cluster.
func (s Spec) SecretName() string { return kube.ResourceName(s.Name, "credentials") }

// ServiceHost is the in-cluster address of a database.
func (s Spec) ServiceHost() string {
	return fmt.Sprintf("%s.%s.svc.cluster.local", s.serviceName(), s.Namespace)
}

func (s Spec) serviceName() string {
	if s.Engine == EnginePostgres {
		// CloudNativePG creates <cluster>-rw for the primary, which is what an
		// application should connect to: writing to a replica fails.
		return s.Name + "-rw"
	}
	return s.Name
}

// Port is the port the database listens on.
func (s Spec) Port() int { return DefaultPorts[s.Engine] }

// ConnectionURL builds the URL an app uses to connect.
func (s Spec) ConnectionURL() string {
	switch s.Engine {
	case EnginePostgres:
		return fmt.Sprintf("postgresql://%s:%s@%s:%d/%s?sslmode=disable",
			s.Username, s.Password, s.ServiceHost(), s.Port(), s.DatabaseName)
	case EngineRedis:
		return fmt.Sprintf("redis://default:%s@%s:%d", s.Password, s.ServiceHost(), s.Port())
	case EngineMySQL:
		return fmt.Sprintf("mysql://%s:%s@%s:%d/%s",
			s.Username, s.Password, s.ServiceHost(), s.Port(), s.DatabaseName)
	default:
		return ""
	}
}

// BuildSecret renders the Secret holding a database's credentials.
func BuildSecret(s Spec) *corev1.Secret {
	data := map[string]string{
		"username": s.Username,
		"password": s.Password,
		"database": s.DatabaseName,
		"host":     s.ServiceHost(),
		"port":     strconv.Itoa(s.Port()),
		"url":      s.ConnectionURL(),
	}
	return &corev1.Secret{
		TypeMeta: metav1.TypeMeta{APIVersion: "v1", Kind: "Secret"},
		ObjectMeta: metav1.ObjectMeta{
			Name: s.SecretName(), Namespace: s.Namespace, Labels: s.Labels(),
		},
		Type:       corev1.SecretTypeOpaque,
		StringData: data,
	}
}

// BuildPostgres renders a CloudNativePG Cluster.
//
// The operator handles failover, backups and minor version upgrades, which is
// the whole reason to use it rather than a StatefulSet we would have to babysit.
func BuildPostgres(s Spec) *unstructured.Unstructured {
	return &unstructured.Unstructured{Object: map[string]any{
		"apiVersion": "postgresql.cnpg.io/v1",
		"kind":       "Cluster",
		"metadata": map[string]any{
			"name":      s.Name,
			"namespace": s.Namespace,
			"labels":    toAnyMap(s.Labels()),
		},
		"spec": map[string]any{
			"instances":             int64(s.Instances),
			"imageName":             fmt.Sprintf("ghcr.io/cloudnative-pg/postgresql:%s", s.Version),
			"primaryUpdateStrategy": "unsupervised",
			"bootstrap": map[string]any{
				"initdb": map[string]any{
					"database": s.DatabaseName,
					"owner":    s.Username,
					"secret":   map[string]any{"name": s.SecretName()},
				},
			},
			"storage": map[string]any{
				"size":         fmt.Sprintf("%dGi", s.StorageGB),
				"storageClass": s.StorageClass,
			},
			"resources": map[string]any{
				"requests": map[string]any{
					"cpu":    fmt.Sprintf("%dm", s.CPURequestM),
					"memory": fmt.Sprintf("%dMi", s.MemRequestMB),
				},
				"limits": map[string]any{
					"memory": fmt.Sprintf("%dMi", s.MemLimitMB),
				},
			},
			"postgresql": map[string]any{
				"parameters": map[string]any{
					// Sized for the container rather than the host: the
					// defaults assume a dedicated machine.
					"shared_buffers":       fmt.Sprintf("%dMB", max(s.MemRequestMB/4, 32)),
					"effective_cache_size": fmt.Sprintf("%dMB", max(s.MemLimitMB/2, 64)),
					"max_connections":      "100",
				},
			},
			"enableSuperuserAccess": false,
		},
	}}
}

// BuildRedis renders a StatefulSet and Service for Redis.
//
// A StatefulSet rather than an operator: a single Redis is a single process
// with a file, and an operator would cost more memory than the database.
func BuildRedis(s Spec) []any {
	labels := s.Labels()
	replicas := int32(1)

	statefulSet := &appsv1.StatefulSet{
		TypeMeta:   metav1.TypeMeta{APIVersion: "apps/v1", Kind: "StatefulSet"},
		ObjectMeta: metav1.ObjectMeta{Name: s.Name, Namespace: s.Namespace, Labels: labels},
		Spec: appsv1.StatefulSetSpec{
			ServiceName: s.Name,
			Replicas:    &replicas,
			Selector:    &metav1.LabelSelector{MatchLabels: selector(labels)},
			Template: corev1.PodTemplateSpec{
				ObjectMeta: metav1.ObjectMeta{Labels: labels},
				Spec: corev1.PodSpec{
					SecurityContext: &corev1.PodSecurityContext{
						RunAsNonRoot: ptr(true),
						RunAsUser:    ptr(int64(999)),
						FSGroup:      ptr(int64(999)),
						// Every environment namespace enforces the restricted
						// Pod Security profile, which refuses a pod that does
						// not name a seccomp profile. Without this the database
						// is never scheduled at all.
						SeccompProfile: &corev1.SeccompProfile{Type: corev1.SeccompProfileTypeRuntimeDefault},
					},
					AutomountServiceAccountToken: ptr(false),
					Containers: []corev1.Container{{
						Name:  "redis",
						Image: fmt.Sprintf("redis:%s-alpine", s.Version),
						// requirepass from an environment variable keeps the
						// password out of the command line, where it would be
						// visible in `ps` inside the container.
						Command: []string{"sh", "-c",
							`exec redis-server --requirepass "$REDIS_PASSWORD" --appendonly yes --dir /data`},
						Env: []corev1.EnvVar{{
							Name: "REDIS_PASSWORD",
							ValueFrom: &corev1.EnvVarSource{
								SecretKeyRef: &corev1.SecretKeySelector{
									LocalObjectReference: corev1.LocalObjectReference{Name: s.SecretName()},
									Key:                  "password",
								},
							},
						}},
						Ports:        []corev1.ContainerPort{{Name: "redis", ContainerPort: int32(s.Port())}},
						VolumeMounts: []corev1.VolumeMount{{Name: "data", MountPath: "/data"}},
						Resources:    resources(s),
						ReadinessProbe: &corev1.Probe{
							ProbeHandler: corev1.ProbeHandler{
								Exec: &corev1.ExecAction{Command: []string{
									"sh", "-c", `redis-cli -a "$REDIS_PASSWORD" ping`,
								}},
							},
							InitialDelaySeconds: 5,
							PeriodSeconds:       10,
						},
						SecurityContext: &corev1.SecurityContext{
							AllowPrivilegeEscalation: ptr(false),
							Capabilities:             &corev1.Capabilities{Drop: []corev1.Capability{"ALL"}},
						},
					}},
				},
			},
			VolumeClaimTemplates: []corev1.PersistentVolumeClaim{{
				ObjectMeta: metav1.ObjectMeta{Name: "data", Labels: labels},
				Spec:       claimSpec(s),
			}},
		},
	}

	return []any{statefulSet, buildService(s, "redis")}
}

// BuildMySQL renders a StatefulSet and Service for MariaDB.
func BuildMySQL(s Spec) []any {
	labels := s.Labels()
	replicas := int32(1)

	statefulSet := &appsv1.StatefulSet{
		TypeMeta:   metav1.TypeMeta{APIVersion: "apps/v1", Kind: "StatefulSet"},
		ObjectMeta: metav1.ObjectMeta{Name: s.Name, Namespace: s.Namespace, Labels: labels},
		Spec: appsv1.StatefulSetSpec{
			ServiceName: s.Name,
			Replicas:    &replicas,
			Selector:    &metav1.LabelSelector{MatchLabels: selector(labels)},
			Template: corev1.PodTemplateSpec{
				ObjectMeta: metav1.ObjectMeta{Labels: labels},
				Spec: corev1.PodSpec{
					SecurityContext: &corev1.PodSecurityContext{
						RunAsNonRoot: ptr(true),
						RunAsUser:    ptr(int64(999)),
						FSGroup:      ptr(int64(999)),
						// Every environment namespace enforces the restricted
						// Pod Security profile, which refuses a pod that does
						// not name a seccomp profile. Without this the database
						// is never scheduled at all.
						SeccompProfile: &corev1.SeccompProfile{Type: corev1.SeccompProfileTypeRuntimeDefault},
					},
					AutomountServiceAccountToken: ptr(false),
					Containers: []corev1.Container{{
						Name:  "mariadb",
						Image: fmt.Sprintf("mariadb:%s", s.Version),
						Env: []corev1.EnvVar{
							secretEnv("MARIADB_ROOT_PASSWORD", s.SecretName(), "password"),
							secretEnv("MARIADB_PASSWORD", s.SecretName(), "password"),
							secretEnv("MARIADB_USER", s.SecretName(), "username"),
							secretEnv("MARIADB_DATABASE", s.SecretName(), "database"),
						},
						Ports:        []corev1.ContainerPort{{Name: "mysql", ContainerPort: int32(s.Port())}},
						VolumeMounts: []corev1.VolumeMount{{Name: "data", MountPath: "/var/lib/mysql"}},
						Resources:    resources(s),
						ReadinessProbe: &corev1.Probe{
							ProbeHandler: corev1.ProbeHandler{
								Exec: &corev1.ExecAction{Command: []string{"healthcheck.sh", "--connect", "--innodb_initialized"}},
							},
							InitialDelaySeconds: 15,
							PeriodSeconds:       10,
						},
						SecurityContext: &corev1.SecurityContext{
							AllowPrivilegeEscalation: ptr(false),
							Capabilities:             &corev1.Capabilities{Drop: []corev1.Capability{"ALL"}},
						},
					}},
				},
			},
			VolumeClaimTemplates: []corev1.PersistentVolumeClaim{{
				ObjectMeta: metav1.ObjectMeta{Name: "data", Labels: labels},
				Spec:       claimSpec(s),
			}},
		},
	}

	return []any{statefulSet, buildService(s, "mysql")}
}

func buildService(s Spec, portName string) *corev1.Service {
	return &corev1.Service{
		TypeMeta:   metav1.TypeMeta{APIVersion: "v1", Kind: "Service"},
		ObjectMeta: metav1.ObjectMeta{Name: s.Name, Namespace: s.Namespace, Labels: s.Labels()},
		Spec: corev1.ServiceSpec{
			Selector: selector(s.Labels()),
			Ports: []corev1.ServicePort{{
				Name: portName, Port: int32(s.Port()), TargetPort: intstr.FromString(portName),
			}},
		},
	}
}

func claimSpec(s Spec) corev1.PersistentVolumeClaimSpec {
	spec := corev1.PersistentVolumeClaimSpec{
		AccessModes: []corev1.PersistentVolumeAccessMode{corev1.ReadWriteOnce},
		Resources: corev1.VolumeResourceRequirements{
			Requests: corev1.ResourceList{
				corev1.ResourceStorage: resource.MustParse(fmt.Sprintf("%dGi", s.StorageGB)),
			},
		},
	}
	if s.StorageClass != "" {
		spec.StorageClassName = &s.StorageClass
	}
	return spec
}

func resources(s Spec) corev1.ResourceRequirements {
	return corev1.ResourceRequirements{
		Requests: corev1.ResourceList{
			corev1.ResourceCPU:    resource.MustParse(fmt.Sprintf("%dm", s.CPURequestM)),
			corev1.ResourceMemory: resource.MustParse(fmt.Sprintf("%dMi", s.MemRequestMB)),
		},
		Limits: corev1.ResourceList{
			corev1.ResourceMemory: resource.MustParse(fmt.Sprintf("%dMi", s.MemLimitMB)),
		},
	}
}

func secretEnv(name, secret, key string) corev1.EnvVar {
	return corev1.EnvVar{
		Name: name,
		ValueFrom: &corev1.EnvVarSource{
			SecretKeyRef: &corev1.SecretKeySelector{
				LocalObjectReference: corev1.LocalObjectReference{Name: secret},
				Key:                  key,
			},
		},
	}
}

// selector is the subset of labels a StatefulSet matches on. A StatefulSet's
// selector is immutable, so it must contain only labels that never change.
func selector(labels map[string]string) map[string]string {
	return map[string]string{
		"app.kubernetes.io/name":      labels["app.kubernetes.io/name"],
		"app.kubernetes.io/component": "database",
	}
}

func toAnyMap(m map[string]string) map[string]any {
	out := make(map[string]any, len(m))
	for k, v := range m {
		out[k] = v
	}
	return out
}

func ptr[T any](v T) *T { return &v }
