-- Initial schema.
--
-- Conventions:
--   * ids are text, generated by the application (prefix_ulid) so they are
--     sortable, copy-pasteable and safe to show in URLs;
--   * timestamps are stored as RFC3339 UTC text, which SQLite compares correctly
--     and a human can read in a backup;
--   * anything named *_enc holds a crypto envelope, never plaintext.

CREATE TABLE users (
    id             TEXT PRIMARY KEY,
    email          TEXT NOT NULL UNIQUE COLLATE NOCASE,
    name           TEXT NOT NULL DEFAULT '',
    password_hash  TEXT NOT NULL,
    totp_secret_enc TEXT NOT NULL DEFAULT '',
    totp_enabled   INTEGER NOT NULL DEFAULT 0,
    is_admin       INTEGER NOT NULL DEFAULT 0,
    disabled       INTEGER NOT NULL DEFAULT 0,
    locale         TEXT NOT NULL DEFAULT '',
    theme          TEXT NOT NULL DEFAULT 'system',
    recovery_saved INTEGER NOT NULL DEFAULT 0,
    created_at     TEXT NOT NULL,
    updated_at     TEXT NOT NULL,
    last_login_at  TEXT
);

CREATE TABLE teams (
    id         TEXT PRIMARY KEY,
    name       TEXT NOT NULL,
    slug       TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL
);

CREATE TABLE memberships (
    team_id    TEXT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role       TEXT NOT NULL CHECK (role IN ('owner','admin','member')),
    created_at TEXT NOT NULL,
    PRIMARY KEY (team_id, user_id)
);
CREATE INDEX idx_memberships_user ON memberships(user_id);

CREATE TABLE projects (
    id          TEXT PRIMARY KEY,
    team_id     TEXT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    name        TEXT NOT NULL,
    slug        TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    created_at  TEXT NOT NULL,
    updated_at  TEXT NOT NULL,
    UNIQUE (team_id, slug)
);

CREATE TABLE environments (
    id         TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    name       TEXT NOT NULL,
    slug       TEXT NOT NULL,
    kind       TEXT NOT NULL DEFAULT 'standard' CHECK (kind IN ('standard','preview')),
    namespace  TEXT NOT NULL UNIQUE,
    -- Preview environments remember what created them so they can be cleaned up.
    source_ref TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    UNIQUE (project_id, slug)
);

CREATE TABLE servers (
    id            TEXT PRIMARY KEY,
    team_id       TEXT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    name          TEXT NOT NULL,
    host          TEXT NOT NULL,
    ssh_port      INTEGER NOT NULL DEFAULT 22,
    ssh_user      TEXT NOT NULL DEFAULT 'root',
    -- The panel's own private key for this server. A password, when one was used
    -- to bootstrap, is never stored: it is used once to install this key.
    ssh_key_enc   TEXT NOT NULL DEFAULT '',
    host_key      TEXT NOT NULL DEFAULT '',
    role          TEXT NOT NULL DEFAULT 'worker' CHECK (role IN ('control-plane','worker')),
    status        TEXT NOT NULL DEFAULT 'pending',
    status_detail TEXT NOT NULL DEFAULT '',
    node_name     TEXT NOT NULL DEFAULT '',
    external_ip   TEXT NOT NULL DEFAULT '',
    internal_ip   TEXT NOT NULL DEFAULT '',
    os_info       TEXT NOT NULL DEFAULT '',
    arch          TEXT NOT NULL DEFAULT '',
    cpu_cores     INTEGER NOT NULL DEFAULT 0,
    memory_mb     INTEGER NOT NULL DEFAULT 0,
    disk_gb       INTEGER NOT NULL DEFAULT 0,
    labels        TEXT NOT NULL DEFAULT '{}',
    created_at    TEXT NOT NULL,
    updated_at    TEXT NOT NULL,
    last_seen_at  TEXT,
    UNIQUE (team_id, host, ssh_port)
);

-- One row per step of a long-running operation (adding a server, a deploy, a
-- restore). Persisting them is what makes those operations resumable and lets
-- the UI redraw progress after a page reload.
CREATE TABLE operations (
    id          TEXT PRIMARY KEY,
    team_id     TEXT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    kind        TEXT NOT NULL,
    target_type TEXT NOT NULL,
    target_id   TEXT NOT NULL,
    status      TEXT NOT NULL CHECK (status IN ('pending','running','succeeded','failed','cancelled')),
    error_code  TEXT NOT NULL DEFAULT '',
    error_msg   TEXT NOT NULL DEFAULT '',
    created_by  TEXT NOT NULL DEFAULT '',
    created_at  TEXT NOT NULL,
    updated_at  TEXT NOT NULL,
    finished_at TEXT
);
CREATE INDEX idx_operations_target ON operations(target_type, target_id);

CREATE TABLE operation_steps (
    id           TEXT PRIMARY KEY,
    operation_id TEXT NOT NULL REFERENCES operations(id) ON DELETE CASCADE,
    seq          INTEGER NOT NULL,
    key          TEXT NOT NULL,
    status       TEXT NOT NULL CHECK (status IN ('pending','running','succeeded','failed','skipped')),
    message      TEXT NOT NULL DEFAULT '',
    detail       TEXT NOT NULL DEFAULT '',
    started_at   TEXT,
    finished_at  TEXT,
    UNIQUE (operation_id, seq)
);

CREATE TABLE git_sources (
    id          TEXT PRIMARY KEY,
    team_id     TEXT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    kind        TEXT NOT NULL CHECK (kind IN ('github_app','github_pat','gitlab','gitea','generic')),
    name        TEXT NOT NULL,
    base_url    TEXT NOT NULL DEFAULT '',
    account     TEXT NOT NULL DEFAULT '',
    config_enc  TEXT NOT NULL DEFAULT '',
    created_at  TEXT NOT NULL,
    updated_at  TEXT NOT NULL
);

CREATE TABLE apps (
    id              TEXT PRIMARY KEY,
    environment_id  TEXT NOT NULL REFERENCES environments(id) ON DELETE CASCADE,
    name            TEXT NOT NULL,
    slug            TEXT NOT NULL,
    source_type     TEXT NOT NULL DEFAULT 'git' CHECK (source_type IN ('git','image','compose')),
    git_source_id   TEXT REFERENCES git_sources(id) ON DELETE SET NULL,
    repo_url        TEXT NOT NULL DEFAULT '',
    branch          TEXT NOT NULL DEFAULT '',
    root_dir        TEXT NOT NULL DEFAULT '',
    builder         TEXT NOT NULL DEFAULT 'auto',
    dockerfile_path TEXT NOT NULL DEFAULT '',
    image           TEXT NOT NULL DEFAULT '',
    port            INTEGER NOT NULL DEFAULT 0,
    health_path     TEXT NOT NULL DEFAULT '',
    start_command   TEXT NOT NULL DEFAULT '',
    replicas        INTEGER NOT NULL DEFAULT 1,
    autoscale       INTEGER NOT NULL DEFAULT 0,
    min_replicas    INTEGER NOT NULL DEFAULT 1,
    max_replicas    INTEGER NOT NULL DEFAULT 3,
    cpu_target      INTEGER NOT NULL DEFAULT 75,
    memory_target   INTEGER NOT NULL DEFAULT 0,
    scale_to_zero   INTEGER NOT NULL DEFAULT 0,
    cpu_request_m   INTEGER NOT NULL DEFAULT 50,
    cpu_limit_m     INTEGER NOT NULL DEFAULT 1000,
    mem_request_mb  INTEGER NOT NULL DEFAULT 128,
    mem_limit_mb    INTEGER NOT NULL DEFAULT 512,
    auto_deploy     INTEGER NOT NULL DEFAULT 1,
    preview_deploys INTEGER NOT NULL DEFAULT 0,
    status          TEXT NOT NULL DEFAULT 'created',
    created_at      TEXT NOT NULL,
    updated_at      TEXT NOT NULL,
    UNIQUE (environment_id, slug)
);

CREATE TABLE app_variables (
    id         TEXT PRIMARY KEY,
    app_id     TEXT NOT NULL REFERENCES apps(id) ON DELETE CASCADE,
    key        TEXT NOT NULL,
    value_enc  TEXT NOT NULL,
    is_secret  INTEGER NOT NULL DEFAULT 0,
    build_time INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE (app_id, key)
);

-- Variables shared by every app in a project, the Railway idea.
CREATE TABLE shared_variables (
    id         TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    key        TEXT NOT NULL,
    value_enc  TEXT NOT NULL,
    is_secret  INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE (project_id, key)
);

CREATE TABLE domains (
    id         TEXT PRIMARY KEY,
    app_id     TEXT NOT NULL REFERENCES apps(id) ON DELETE CASCADE,
    hostname   TEXT NOT NULL UNIQUE,
    path       TEXT NOT NULL DEFAULT '/',
    tls        INTEGER NOT NULL DEFAULT 1,
    auto       INTEGER NOT NULL DEFAULT 0,
    status     TEXT NOT NULL DEFAULT 'pending',
    status_detail TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL
);

CREATE TABLE deployments (
    id                TEXT PRIMARY KEY,
    app_id            TEXT NOT NULL REFERENCES apps(id) ON DELETE CASCADE,
    number            INTEGER NOT NULL,
    status            TEXT NOT NULL CHECK (status IN ('queued','building','deploying','succeeded','failed','cancelled','superseded')),
    trigger           TEXT NOT NULL DEFAULT 'manual',
    commit_sha        TEXT NOT NULL DEFAULT '',
    commit_message    TEXT NOT NULL DEFAULT '',
    commit_author     TEXT NOT NULL DEFAULT '',
    image             TEXT NOT NULL DEFAULT '',
    -- The two halves of ADR-0007. A change to runtime_spec alone never rebuilds.
    build_fingerprint TEXT NOT NULL DEFAULT '',
    runtime_spec      TEXT NOT NULL DEFAULT '{}',
    error_code        TEXT NOT NULL DEFAULT '',
    error_message     TEXT NOT NULL DEFAULT '',
    error_hint        TEXT NOT NULL DEFAULT '',
    created_by        TEXT NOT NULL DEFAULT '',
    created_at        TEXT NOT NULL,
    started_at        TEXT,
    finished_at       TEXT,
    UNIQUE (app_id, number)
);
CREATE INDEX idx_deployments_app ON deployments(app_id, number DESC);

CREATE TABLE build_logs (
    id            TEXT PRIMARY KEY,
    deployment_id TEXT NOT NULL REFERENCES deployments(id) ON DELETE CASCADE,
    seq           INTEGER NOT NULL,
    stream        TEXT NOT NULL DEFAULT 'stdout',
    line          TEXT NOT NULL,
    at            TEXT NOT NULL,
    UNIQUE (deployment_id, seq)
);

CREATE TABLE volumes (
    id            TEXT PRIMARY KEY,
    app_id        TEXT NOT NULL REFERENCES apps(id) ON DELETE CASCADE,
    name          TEXT NOT NULL,
    mount_path    TEXT NOT NULL,
    size_gb       INTEGER NOT NULL DEFAULT 1,
    storage_class TEXT NOT NULL DEFAULT '',
    created_at    TEXT NOT NULL,
    UNIQUE (app_id, name)
);

CREATE TABLE databases (
    id              TEXT PRIMARY KEY,
    environment_id  TEXT NOT NULL REFERENCES environments(id) ON DELETE CASCADE,
    name            TEXT NOT NULL,
    slug            TEXT NOT NULL,
    engine          TEXT NOT NULL CHECK (engine IN ('postgres','redis','mysql')),
    engine_version  TEXT NOT NULL DEFAULT '',
    status          TEXT NOT NULL DEFAULT 'creating',
    status_detail   TEXT NOT NULL DEFAULT '',
    instances       INTEGER NOT NULL DEFAULT 1,
    storage_gb      INTEGER NOT NULL DEFAULT 5,
    cpu_request_m   INTEGER NOT NULL DEFAULT 100,
    mem_request_mb  INTEGER NOT NULL DEFAULT 256,
    credentials_enc TEXT NOT NULL DEFAULT '',
    created_at      TEXT NOT NULL,
    updated_at      TEXT NOT NULL,
    UNIQUE (environment_id, slug)
);

-- Which apps get a connection string injected for which database.
CREATE TABLE database_links (
    database_id TEXT NOT NULL REFERENCES databases(id) ON DELETE CASCADE,
    app_id      TEXT NOT NULL REFERENCES apps(id) ON DELETE CASCADE,
    var_name    TEXT NOT NULL,
    created_at  TEXT NOT NULL,
    PRIMARY KEY (database_id, app_id)
);

CREATE TABLE backup_policies (
    id           TEXT PRIMARY KEY,
    target_type  TEXT NOT NULL CHECK (target_type IN ('database','volume')),
    target_id    TEXT NOT NULL,
    schedule     TEXT NOT NULL DEFAULT '0 3 * * *',
    retention    INTEGER NOT NULL DEFAULT 7,
    destination  TEXT NOT NULL DEFAULT 's3',
    enabled      INTEGER NOT NULL DEFAULT 1,
    created_at   TEXT NOT NULL,
    updated_at   TEXT NOT NULL,
    UNIQUE (target_type, target_id)
);

CREATE TABLE backups (
    id           TEXT PRIMARY KEY,
    target_type  TEXT NOT NULL,
    target_id    TEXT NOT NULL,
    status       TEXT NOT NULL CHECK (status IN ('running','succeeded','failed')),
    kind         TEXT NOT NULL DEFAULT 'scheduled',
    location     TEXT NOT NULL DEFAULT '',
    size_bytes   INTEGER NOT NULL DEFAULT 0,
    error_message TEXT NOT NULL DEFAULT '',
    created_at   TEXT NOT NULL,
    finished_at  TEXT
);
CREATE INDEX idx_backups_target ON backups(target_type, target_id, created_at DESC);

CREATE TABLE sessions (
    id         TEXT PRIMARY KEY,
    user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL UNIQUE,
    ip         TEXT NOT NULL DEFAULT '',
    user_agent TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    last_seen_at TEXT NOT NULL,
    expires_at TEXT NOT NULL
);
CREATE INDEX idx_sessions_user ON sessions(user_id);

CREATE TABLE api_tokens (
    id           TEXT PRIMARY KEY,
    user_id      TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    team_id      TEXT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    name         TEXT NOT NULL,
    token_hash   TEXT NOT NULL UNIQUE,
    prefix       TEXT NOT NULL,
    scopes       TEXT NOT NULL DEFAULT '',
    created_at   TEXT NOT NULL,
    last_used_at TEXT,
    expires_at   TEXT
);

CREATE TABLE login_attempts (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    identifier TEXT NOT NULL,
    ip         TEXT NOT NULL,
    success    INTEGER NOT NULL,
    at         TEXT NOT NULL
);
CREATE INDEX idx_login_attempts_lookup ON login_attempts(identifier, at);
CREATE INDEX idx_login_attempts_ip ON login_attempts(ip, at);

CREATE TABLE audit_events (
    id          TEXT PRIMARY KEY,
    team_id     TEXT NOT NULL DEFAULT '',
    actor_id    TEXT NOT NULL DEFAULT '',
    actor_label TEXT NOT NULL DEFAULT '',
    action      TEXT NOT NULL,
    target_type TEXT NOT NULL DEFAULT '',
    target_id   TEXT NOT NULL DEFAULT '',
    target_label TEXT NOT NULL DEFAULT '',
    ip          TEXT NOT NULL DEFAULT '',
    user_agent  TEXT NOT NULL DEFAULT '',
    metadata    TEXT NOT NULL DEFAULT '{}',
    at          TEXT NOT NULL
);
CREATE INDEX idx_audit_team_time ON audit_events(team_id, at DESC);

-- Runtime configuration an operator edits in the panel: wildcard domain, GitHub
-- App, S3, SMTP, DNS provider. Never in code, never in a file the user edits.
CREATE TABLE settings (
    key        TEXT PRIMARY KEY,
    value      TEXT NOT NULL DEFAULT '',
    encrypted  INTEGER NOT NULL DEFAULT 0,
    updated_at TEXT NOT NULL,
    updated_by TEXT NOT NULL DEFAULT ''
);

CREATE TABLE notification_channels (
    id         TEXT PRIMARY KEY,
    team_id    TEXT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    kind       TEXT NOT NULL CHECK (kind IN ('email','telegram','discord','webhook')),
    name       TEXT NOT NULL,
    config_enc TEXT NOT NULL DEFAULT '',
    events     TEXT NOT NULL DEFAULT '',
    enabled    INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

-- Which optional cluster components have been installed, so the panel installs
-- each one exactly once and can show its version.
CREATE TABLE cluster_components (
    name         TEXT PRIMARY KEY,
    status       TEXT NOT NULL DEFAULT 'absent',
    version      TEXT NOT NULL DEFAULT '',
    installed_at TEXT,
    detail       TEXT NOT NULL DEFAULT ''
);
