id: babybuddy
name: Babybuddy
description: It helps parents track their baby's daily activities, growth, and health with ease.
category: productivity
website: https://docs.baby-buddy.net
services:
- name: babybuddy
  image: linuxserver/babybuddy:2.10.1
  port: 8000
  public: true
  mem_request_mb: 128
  mem_limit_mb: 1024
  cpu_request_m: 50
  cpu_limit_m: 1000
  variables:
    PUID: '1000'
    PGID: '1000'
    TZ: Europe/Madrid
  volumes:
  - name: babybuddy-config
    mount_path: /config
    size_gb: 5
