id: convertx
name: Convertx
description: A self-hosted online file converter. Supports over a thousand different formats.
category: developer
website: https://github.com/C4illin/ConvertX
services:
- name: convertx
  image: ghcr.io/c4illin/convertx:v0.18.0
  port: 3000
  public: true
  mem_request_mb: 128
  mem_limit_mb: 1024
  cpu_request_m: 50
  cpu_limit_m: 1000
  volumes:
  - name: convertx-data
    mount_path: /app/data
    size_gb: 5
