id: dolibarr
name: Dolibarr
description: Dolibarr is a modern software package to manage your organization's activity (contacts, quotes,
  invoices, orders, stocks, agenda, hr, expense reports, accountancy, ecm, manufacturing, ...).
category: productivity
website: https://www.dolibarr.org/documentation-home.php
services:
- name: dolibarr
  image: dolibarr/dolibarr:24
  port: 80
  public: true
  mem_request_mb: 128
  mem_limit_mb: 1024
  cpu_request_m: 50
  cpu_limit_m: 1000
  volumes:
  - name: dolibarr-docs
    mount_path: /var/www/documents
    size_gb: 5
  - name: dolibarr-custom
    mount_path: /var/www/html/custom
    size_gb: 5
databases:
- name: dolibarr-db
  engine: mysql
  storage_gb: 5
  link_to:
  - dolibarr
  var_name: DATABASE_URL
