id: dozzle-with-auth
name: Dozzle With Auth
description: Dozzle is a simple and lightweight web UI for Docker logs.
category: developer
website: https://dozzle.dev/
services:
- name: dozzle
  image: amir20/dozzle:v11.1
  port: 8080
  public: true
  mem_request_mb: 128
  mem_limit_mb: 1024
  cpu_request_m: 50
  cpu_limit_m: 1000
  variables:
    DOZZLE_AUTH_PROVIDER: simple
