id: electricsql
name: Electricsql
description: Sync shape-based subsets of your Postgres data over HTTP.
category: developer
website: https://electric-sql.com/docs/guides/deployment
services:
- name: electric
  image: electricsql/electric:1.4.2
  port: 3000
  public: true
  mem_request_mb: 128
  mem_limit_mb: 1024
  cpu_request_m: 50
  cpu_limit_m: 1000
  variables:
    ELECTRIC_STORAGE_DIR: /app/persistent
  volumes:
  - name: electric-data
    mount_path: /app/persistent
    size_gb: 5
