id: emby
name: Emby
description: A media server software that allows you to organize, stream, and access your multimedia content
  effortlessly.
category: media
website: https://emby.media/support/articles/Home.html
services:
- name: emby
  image: linuxserver/emby:4.10.0
  port: 8096
  public: true
  mem_request_mb: 128
  mem_limit_mb: 1024
  cpu_request_m: 50
  cpu_limit_m: 1000
  variables:
    PUID: '1000'
    PGID: '1000'
    TZ: Europe/Madrid
  volumes:
  - name: emby-config
    mount_path: /config
    size_gb: 5
  - name: emby-tvshows
    mount_path: /tvshows
    size_gb: 5
