id: esphome
name: Esphome
description: Smart Home Made Simple.
category: automation
website: https://esphome.io/guides/getting_started_command_line/
services:
- name: esphome
  image: ghcr.io/esphome/esphome:2025.12.4
  port: 6052
  public: true
  mem_request_mb: 128
  mem_limit_mb: 1024
  cpu_request_m: 50
  cpu_limit_m: 1000
  volumes:
  - name: esp-config
    mount_path: /config
    size_gb: 5
