id: gowa
name: Gowa
description: Golang WhatsApp - Built with Go for efficient memory use.
category: communication
website: https://github.com/aldinokemal/go-whatsapp-web-multidevice
services:
- name: gowa
  image: aldinokemal2104/go-whatsapp-web-multidevice:v9.3.1
  port: 3000
  public: true
  mem_request_mb: 128
  mem_limit_mb: 1024
  cpu_request_m: 50
  cpu_limit_m: 1000
  variables:
    APP_PORT: '3000'
  volumes:
  - name: gowa-data
    mount_path: /app/storages
    size_gb: 5
