id: grimmory
name: Grimmory
description: Grimmory is a self-hosted application for managing your entire book collection in one place.
  Organize, read, annotate, sync across devices, and share without relying on third-party services.
category: other
website: https://github.com/grimmory-tools/grimmory
services:
- name: grimmory
  image: grimmory/grimmory:v3.4
  port: 80
  public: true
  mem_request_mb: 128
  mem_limit_mb: 1024
  cpu_request_m: 50
  cpu_limit_m: 1000
  variables:
    BOOKLORE_PORT: '80'
  volumes:
  - name: grimmory-data
    mount_path: /app/data
    size_gb: 5
  - name: grimmory-books
    mount_path: /books
    size_gb: 5
databases:
- name: grimmory-db
  engine: mysql
  storage_gb: 5
  link_to: grimmory
  var_name: DATABASE_URL
