id: grist
name: Grist
description: Grist is a modern relational spreadsheet. It combines the flexibility of a spreadsheet with
  the robustness of a database.
category: productivity
website: https://support.getgrist.com/
services:
- name: grist
  image: gristlabs/grist:1.7
  port: 8484
  public: true
  mem_request_mb: 128
  mem_limit_mb: 1024
  cpu_request_m: 50
  cpu_limit_m: 1000
  volumes:
  - name: grist-data
    mount_path: /persist
    size_gb: 5
databases:
- name: grist-db
  engine: postgres
  storage_gb: 5
  link_to:
  - grist
  var_name: DATABASE_URL
