id: homebox
name: Homebox
description: Homebox is the inventory and organization system built for the Home User.
category: productivity
website: https://github.com/sysadminsmedia/homebox
services:
- name: homebox
  image: ghcr.io/sysadminsmedia/homebox:0.15
  port: 7745
  public: true
  mem_request_mb: 128
  mem_limit_mb: 1024
  cpu_request_m: 50
  cpu_limit_m: 1000
  volumes:
  - name: homebox-data
    mount_path: /data
    size_gb: 5
