id: limesurvey
name: Limesurvey
description: Simple, quick and anonymous online survey tool that's bursting with juicy insights.
category: productivity
website: https://www.limesurvey.org/manual/
services:
- name: limesurvey
  image: adamzammit/limesurvey:7.1.1
  port: 80
  public: true
  mem_request_mb: 128
  mem_limit_mb: 1024
  cpu_request_m: 50
  cpu_limit_m: 1000
  variables:
    LIMESURVEY_PHP_SESSION_SAVE_PATH: tcp://redis:6379
  volumes:
  - name: limesurvey-plugins-data
    mount_path: /var/www/html/plugins
    size_gb: 5
  - name: limesurvey-upload-data
    mount_path: /var/www/html/upload
    size_gb: 5
databases:
- name: limesurvey-db
  engine: mysql
  storage_gb: 5
  link_to: limesurvey
  var_name: DATABASE_URL
