id: lobe-chat
name: Lobe Chat
description: An open-source, modern-design AI chat framework.
category: ai
website: https://github.com/lobehub/lobe-chat
services:
- name: lobe-chat
  image: lobehub/lobe-chat:1.135.5
  port: 3210
  public: true
  mem_request_mb: 128
  mem_limit_mb: 1024
  cpu_request_m: 50
  cpu_limit_m: 1000
