id: logto
name: Logto
description: A comprehensive identity solution covering both the front and backend, complete with pre-built
  infrastructure and enterprise-grade solutions.
category: security
website: https://docs.logto.io/docs/tutorials/get-started/#logto-oss-self-hosted
services:
- name: logto
  image: svhd/logto:1.43
  port: 3001
  public: true
  mem_request_mb: 128
  mem_limit_mb: 1024
  cpu_request_m: 50
  cpu_limit_m: 1000
  variables:
    TRUST_PROXY_HEADER: '1'
databases:
- name: logto-db
  engine: postgres
  storage_gb: 5
  link_to:
  - logto
  var_name: DATABASE_URL
