id: moodle
name: Moodle
description: Moodle is the world’s most customisable and trusted eLearning solution that empowers educators
  to improve our world.
category: cms
website: https://moodle.org
services:
- name: moodle
  image: bitnamilegacy/moodle:4.3
  port: 8080
  public: true
  mem_request_mb: 128
  mem_limit_mb: 1024
  cpu_request_m: 50
  cpu_limit_m: 1000
  variables:
    MOODLE_DATABASE_PORT_NUMBER: '3306'
    MOODLE_DATABASE_NAME: bitnami_moodle
    ALLOW_EMPTY_PASSWORD: 'no'
    MOODLE_EMAIL: user@example.com
  volumes:
  - name: moodle-data
    mount_path: /bitnami/moodle
    size_gb: 5
  - name: moodledata-data
    mount_path: /bitnami/moodledata
    size_gb: 5
databases:
- name: moodle-db
  engine: mysql
  storage_gb: 5
  link_to:
  - moodle
  var_name: DATABASE_URL
