id: navidrome
name: Navidrome
description: Standalone server, that allows you to browse and listen to your music collection using a
  web browser or any Subsonic-compatible client.
category: media
website: https://www.navidrome.org/docs/
services:
- name: navidrome
  image: deluan/navidrome:0.64.0
  port: 4533
  public: true
  mem_request_mb: 128
  mem_limit_mb: 1024
  cpu_request_m: 50
  cpu_limit_m: 1000
