id: newapi
name: Newapi
description: The next-generation LLM gateway and AI asset management system supports multiple languages.
category: developer
website: https://docs.newapi.pro/en/getting-started/
services:
- name: new-api
  image: calciumion/new-api:v0.13.2
  port: 3000
  public: true
  mem_request_mb: 128
  mem_limit_mb: 1024
  cpu_request_m: 50
  cpu_limit_m: 1000
  variables:
    REDIS_CONN_STRING: redis://redis:6379
databases:
- name: newapi-db
  engine: postgres
  storage_gb: 5
  link_to: new-api
  var_name: DATABASE_URL
