id: nocodb
name: Nocodb
description: NocoDB is an open source Airtable alternative. Turns any MySQL, PostgreSQL, SQL Server, SQLite
  & MariaDB into a smart-spreadsheet.
category: productivity
website: https://nocodb.com/
services:
- name: nocodb
  image: nocodb/nocodb:2026.09.0
  port: 8080
  public: true
  mem_request_mb: 128
  mem_limit_mb: 1024
  cpu_request_m: 50
  cpu_limit_m: 1000
  volumes:
  - name: nocodb-data
    mount_path: /usr/app/data/
    size_gb: 5
