id: pairdrop
name: Pairdrop
description: Pairdrop is a self-hosted file sharing and collaboration platform, offering secure file sharing
  and collaboration capabilities for efficient teamwork.
category: productivity
website: https://pairdrop.net/
services:
- name: pairdrop
  image: linuxserver/pairdrop:1.11.2
  port: 3000
  public: true
  mem_request_mb: 128
  mem_limit_mb: 1024
  cpu_request_m: 50
  cpu_limit_m: 1000
  variables:
    PUID: '1000'
    PGID: '1000'
    TZ: Europe/Madrid
    DEBUG_MODE: 'false'
