id: postiz
name: Postiz
description: Open source social media scheduling tool.
category: analytics
website: https://docs.postiz.com
services:
- name: postiz
  image: ghcr.io/gitroomhq/postiz-app:v2.10.1
  port: 5000
  public: true
  mem_request_mb: 128
  mem_limit_mb: 1024
  cpu_request_m: 50
  cpu_limit_m: 1000
  variables:
    BACKEND_INTERNAL_URL: http://localhost:3000
    IS_GENERAL: 'true'
  volumes:
  - name: postiz-config
    mount_path: /config/
    size_gb: 5
  - name: postiz-uploads
    mount_path: /uploads/
    size_gb: 5
databases:
- name: postiz-db
  engine: postgres
  storage_gb: 5
  link_to: postiz
  var_name: DATABASE_URL
