id: rabbitmq
name: Rabbitmq
description: With tens of thousands of users, RabbitMQ is one of the most popular open source message
  brokers.
category: communication
website: https://www.rabbitmq.com/documentation.html
services:
- name: rabbitmq
  image: rabbitmq:3-management
  port: 15672
  public: true
  mem_request_mb: 128
  mem_limit_mb: 1024
  cpu_request_m: 50
  cpu_limit_m: 1000
  volumes:
  - name: rabbitmq-data
    mount_path: /var/lib/rabbitmq/
    size_gb: 5
