id: sequin
name: Sequin
description: The fastest Postgres change data capture.
category: analytics
website: https://sequinstream.com/docs/
services:
- name: sequin
  image: sequin/sequin:v0.14.6
  port: 7376
  public: true
  mem_request_mb: 128
  mem_limit_mb: 1024
  cpu_request_m: 50
  cpu_limit_m: 1000
  variables:
    PG_POOL_SIZE: '20'
    CONFIG_FILE_PATH: /config/playground.yml
databases:
- name: sequin-db
  engine: postgres
  storage_gb: 5
  link_to: sequin
  var_name: DATABASE_URL
