id: swetrix
name: Swetrix
description: Privacy-friendly and cookieless European web analytics alternative to Google Analytics.
category: analytics
website: https://docs.swetrix.com/selfhosting/how-to
services:
- name: swetrix
  image: swetrix/swetrix-fe:v4.0.5
  port: 3000
  public: true
  mem_request_mb: 128
  mem_limit_mb: 1024
  cpu_request_m: 50
  cpu_limit_m: 1000
- name: swetrix-api
  image: swetrix/swetrix-api:v4.0.5
  port: 5005
  public: false
  mem_request_mb: 128
  mem_limit_mb: 1024
  cpu_request_m: 50
  cpu_limit_m: 1000
- name: clickhouse
  image: clickhouse/clickhouse-server:24.10-alpine
  port: 8123
  public: false
  mem_request_mb: 128
  mem_limit_mb: 1024
  cpu_request_m: 50
  cpu_limit_m: 1000
  volumes:
  - name: swetrix-events-data
    mount_path: /var/lib/clickhouse
    size_gb: 5
databases:
- name: swetrix-db
  engine: redis
  storage_gb: 5
  link_to:
  - swetrix
  - swetrix-api
  var_name: DATABASE_URL
notes: This template installs 3 apps. They reach each other by name inside the environment, so keep them
  together.
