id: syncthing
name: Syncthing
description: Syncthing synchronizes files between two or more computers in real time.
category: storage
website: https://syncthing.net/
services:
- name: syncthing
  image: linuxserver/syncthing:2.1.5
  port: 8384
  public: true
  mem_request_mb: 128
  mem_limit_mb: 1024
  cpu_request_m: 50
  cpu_limit_m: 1000
  variables:
    PUID: '1000'
    PGID: '1000'
  volumes:
  - name: syncthing-config
    mount_path: /config
    size_gb: 5
  - name: syncthing-data1
    mount_path: /data1
    size_gb: 5
