id: wakapi
name: Wakapi
description: A minimalist, self-hosted WakaTime-compatible backend for coding statistics.
category: analytics
website: https://wakapi.dev/
services:
- name: wakapi
  image: ghcr.io/muety/wakapi:2.18
  port: 3000
  public: true
  mem_request_mb: 128
  mem_limit_mb: 1024
  cpu_request_m: 50
  cpu_limit_m: 1000
  variables:
    WAKAPI_SERVER_LISTEN_IPV6: '-'
    WAKAPI_MAIL_PROVIDER: smtp
  volumes:
  - name: wakapi-data
    mount_path: /data
    size_gb: 5
databases:
- name: wakapi-db
  engine: postgres
  storage_gb: 5
  link_to:
  - wakapi
  var_name: DATABASE_URL
