id: yamtrack
name: Yamtrack
description: Yamtrack is a self hosted media tracker for movies, tv shows, anime, manga, video games and
  books.
category: productivity
website: https://github.com/FuzzyGrim/Yamtrack/wiki
services:
- name: yamtrack
  image: ghcr.io/fuzzygrim/yamtrack:0.26
  port: 8000
  public: true
  mem_request_mb: 128
  mem_limit_mb: 1024
  cpu_request_m: 50
  cpu_limit_m: 1000
  volumes:
  - name: yamtrack-data
    mount_path: /yamtrack/db
    size_gb: 5
databases:
- name: yamtrack-db
  engine: redis
  storage_gb: 5
  link_to: yamtrack
  var_name: DATABASE_URL
